# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://username.github.io/
baseurl: /
title: Eddy Ionescu
author: Eddy Ionescu
description: Eddy's personal website
avatar: profile.png
email: eddyionescu@gmail.com
github: EddyIonescu # username
linkedin: eduard_ionescu
google_analytics: UA-90625193-1


# needed for travis-ci build
exclude: [vendor]
