# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate, jekyll-redirect-from]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://eddyionescu.com/
baseurl: http://eddyionescu.com/
title: Eddy Ionescu
author: Eddy Ionescu
#description: Eddy's personal website
avatar: profile.png
email: eddyionescu@gmail.com
github: EddyIonescu # username
linkedin: eduard-ionescu
google_analytics: UA-90625193-1

redirect_from:
  - /resume.pdf
  - /eddy_resume.pdf

# needed for travis-ci build
exclude: [vendor]
